#!/usr/bin/env bash

# This is a generic hook that is meant to invoke multiple hooks,
# handling both arguments, stdin, and breaking on the first error

# This makes it easy to write hooks that do exactly one thing

HOOK_NAME="$(basename "${BASH_SOURCE[0]}")"

GIT_DIR="$(git rev-parse --git-dir)"
HOOKS="$GIT_DIR/hooks/$HOOK_NAME.d"
if [[ -d "$HOOKS" ]]; then
    stdin="$(cat; echo x)"
    for HOOK in "$HOOKS"/*; do
        if [[ -f "$HOOK" && -x "$HOOK" ]]; then
            printf "%s" "${stdin%x}" | "$HOOK" "$@" || exit $?
        fi
    done
fi

exit 0
