#!/usr/bin/env bash

# This is a script that installs all the hooks alongside it in the directory to the containing git repo
#
# The intention is that this script is copied from Steven Karas's bashfiles repo (https://github.com/stevenkaras/bashfiles)
# into your project. Please leave this notice in the file so you can find the most up to date version of this script.

HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
HOOKS="applypatch-msg pre-applypatch post-applypatch pre-commit prepare-commit-msg commit-msg post-commit pre-rebase post-checkout post-merge pre-receive update post-receive post-update pre-auto-gc"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# install the given hook
function install_hook() {
    local hook_name="$1"
    local hook_path="$HOOKS_DIR/$hook_name"
    if [[ -e "$hook_path" ]]; then
        return 0
    fi
    if [[ ! -e "$DIR/$hook_name" ]]; then
        return 0
    fi

    ln -sf "$DIR/$hook_name" "$hook_path"
}

#TODO: check if we're in a git repo or not

for hook in $HOOKS; do
    install_hook "$hook"
done
