#!/usr/bin/env bash

# This is a script that installs all the hooks alongside it in the directory to the containing git repo
#
# The intention is that this script is copied from Steven Karas's bashfiles repo (https://github.com/stevenkaras/bashfiles)
# into your project. Please leave this notice in the file so you can find the most up to date version of this script.

HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function remove_broken_symlinks() {
    local ROOTDIR
    ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    local target="$1"

    for file in "$target/"*; do
        if [[ -h "$file" && ! -e "$file" ]]; then
            local symlink_target
            symlink_target="$(readlink -n "$file")"
            [[ "$symlink_target" = "$ROOTDIR"/* ]] && rm "$file"
        fi
    done
}

# install the given hook
function install_hook() {
    local hook_name="$1"
    local hook_path="$HOOKS_DIR/${hook_name%%.*}"
    if [[ -e "$hook_path" ]]; then
        return 0
    fi
    if [[ -e "$DIR/$hook_name" ]]; then
        ln -snfT "$DIR/$hook_name" "$hook_path"
    fi
    if [[ -d "$DIR/$hook_name" ]]; then
        ln -snfT "$DIR/$hook_name" "$hook_path.d"
        ln -snfT dispatching_hook "$hook_path"
    fi
}

# remove any broken hooks
remove_broken_symlinks "$HOOKS_DIR"

for hook in "$DIR"/!("$(basename "${BASH_SOURCE[0]}")"); do
    install_hook "$(basename "$hook")"
done
