#!/bin/bash

__sshca_completion() {
    local current_word=${COMP_WORDS[COMP_CWORD]}
    local previous_word=${COMP_WORDS[COMP_CWORD-1]}
    local all_words=("${COMP_WORDS[@]}")
    local which_word=$COMP_CWORD
    if [[ $current_word == *"="* ]]; then
        previous_word=${current_word%=*}
        current_word=${current_word#*=}
    fi

    local words=""
    if (($which_word == 1)); then
        # display only commands
        words="help setup install revoke sign signhost trustconfig selfdestruct uninstall implode"
    else
        case ${COMP_WORDS[1]} in
        help)
            ;;
        setup)
            #TODO: complete a path
            ;;
        install)
            #TODO: complete ssh hosts/servers
            ;;
        revoke)
            ;;
        sign)
            #TODO: complete paths, then options for ssh-keygen
            ;;
        signhost)
            #TODO: complete paths/ssh hosts/servers, then options for ssh-keygen
            ;;
        trustconfig)
            ;;
        selfdestruct|uninstall|implode)
            ;;
        esac
    fi
    COMPREPLY=($(compgen -W "$words" -- $current_word))
}

complete -o default -o nospace -F __sshca_completion ssh-ca
