#!/bin/bash

__svn_complete_config_option() {
    # TODO: split the current word into key/value
    "server:global:http-library=serf"
}

__svn_complete_global_options() {
    echo "--username --password --no-auth-cache --non-interactive --trust-server-cert --config-dir --config-option"
}

__svn_completion() {
    local current_word=${COMP_WORDS[COMP_CWORD]}
    local previous_word=${COMP_WORDS[COMP_CWORD-1]}
    local all_words=("${COMP_WORDS[@]}")
    local which_word=$COMP_CWORD
    if [[ $current_word == *"="* ]]; then
        previous_word=${current_word%=*}
        current_word=${current_word#*=}
    fi

    local words=""
    case $previous_word in
    checkout|commit) ;;
    cat|changelist|cleanup|export|import) ;;
    info|list|lock|log|merge|unlock) ;;
    mergeinfo|propdel|propedit|propget|proplist|propset);;
    resolve|resolved|revert|status|switch|update) ;;
    rename|ren|add|copy|delete|move|mkdir) ;;
    cl|co|ci|cp|del|remove|rm|di|ls|h|mv) ;;
    pdel|pd|pedit|pe|pget|pg|plist|pl|pset|ps|stat|st|sw|up) ;;

    blame)
        if [[ ${current_word:0:1} == "-" ]]; then
            words="$(__svn_complete_global_options) -r --revision -v --verbose -g --use-merge-history --incremental --xml -x --extensions --force"
        fi
        ;;
    --config-dir) ;; # should complete to a directory
    --config-option) word="$(__svn_complete_config_option)";;
    *)
        if [[ ${current_word:0:1} == "-" ]]; then
            words="--username --password --no-auth-cache --non-interactive --trust-server-cert --config-dir --config-option"
        else
            # display only commands
            words="add blame cat changelist checkout cleanup commit copy delete diff export help import info list lock log merge"
            words="$words mergeinfo mkdir move propdel propedit propget proplist propset resolve resolved revert status switch unlock update"
            words="$words praise annotate ann"
            words="$words cl co ci cp del remove rm di ls h mv rename ren pdel pd pedit pe pget pg plist pl pset ps stat st sw up"
        fi
    esac
    COMPREPLY=($(compgen -W "$words" -- $current_word))
}

complete -o default -o nospace -F __svn_completion svn
